### ISSUE TITLE
Cadastro e edição de pessoa jurídica

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/sigcon#11]
Child of #10

**Comment by riquetinem** [comment]
No edição PJ, ele não esta retornando os dados corretos.

**Comment by Tannair** [comment]
Corrigido.

**Comment by LoreleiGab** [comment]
Ajustado ordem dos campos, variável que se perdia e removido botão Cancelar

**Comment by riquetinem** [comment]
Notice: Undefined variable: endereco_id in /opt/lampp/htdocs/sigcon/perfil/contratos/pessoa_juridica/pj_edita.php on line 165

**Comment by LoreleiGab** [comment]
Corrigido

**Comment by DiegoVSantos** [comment]
TESTE OK!
