### ISSUE TITLE
Cadastro e edição de contratos

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/sigcon#13]
Deve incluir o cadastro da vigência principal e dos aditivos.

**Comment by riquetinem** [comment]
![Screenshot from 2019-01-29 16-13-45.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b7ef1f1eb1e8f001465cf5d/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f37a3dd7ba68ee1436505c424aa953444d04bea6d37ef5f22e7a985958ee8539577d953412afb9d01dbf05b9768e4c86e0bb8b5edcfa7f74b9dfd0126754505a9bf54f34a9934acd5cfe4ce94853a112316ae4647b.png)

**Comment by riquetinem** [comment]
Falta editar/excluir equipamento, travei nisso

**Comment by DiegoVSantos** [comment]
TESTE OK
