### ISSUE TITLE
Cadastro e edição de licitação

### ISSUE THREAD

**Issue by DiegoVSantos** [igsis/sigcon#2]
Child of #1

**Comment by LoreleiGab** [comment]
Cadastro e edição dos campos: Homologação Observação, Empenho Observação e Ordem de Início deve ficar habilitados caso a opção do campo referente à eles seja NÃO.

**Comment by LoreleiGab** [comment]
Ao abrir a tela de edição através do menu Pesquisa, os campos estão vindo com a informação de DISABLE mesmo tendo conteúdo.

**Comment by LoreleiGab** [comment]
Os campos do formulário não estão se habilitando conforme  o preenchimento do campo anterior

**Comment by Tannair** [comment]
Corrigido, campos radios habilitam o seguinte selecionando Sim e desabilitam se a opcao for nao e campos de obs nao mais ficam desabilitados.

**Comment by isaiaszmendes** [comment]
Substituição dos radios por checkbox. Validação do preenchimento dos anteriores e posteriores
