### ISSUE TITLE
Pesquisa / listagem de contratos

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/sigcon#35]
Filtros da pesquisa:
2.6.1.	Número do processo administrativo; 
2.6.2.	Termo de contrato;
2.6.3.	Objeto (completo ou parte do nome);
2.6.4.	Unidade; 
2.6.5.	Equipamentos atendidos;
2.6.6.	Tipo de serviço;
2.6.7.	Razão Social ou Nome;
2.6.8.	CNPJ ou CPF.

Requires #13

**Comment by DiegoVSantos** [comment]
TESTE OK
