### ISSUE TITLE
PESQUISA - Tela inicial / Pesquisa

### ISSUE THREAD

**Issue by LoreleiGab** [igsis/sigcon#38]
A própria tela inicial ser a tela de pesquisa. Deve conter os filtros:
3.1.1.	Número do processo administrativo;
                Número do processo de pagamento;
3.1.2.	Termo de contrato;
3.1.3.	Objeto (completo ou parte do nome);
3.1.4.	Unidade; 
3.1.5.	Equipamentos atendidos;
3.1.6.	Razão Social ou Nome;
3.1.7.	CNPJ ou CPF.

**Comment by DiegoVSantos** [comment]
Teste OK
